---
apiVersion: v1
kind: Service
metadata:
  name: agent
  labels:
    app: agent
spec:
  type: NodePort
  selector:
    app: agent
  ports:
  - protocol: TCP
    port: 9999
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: agent
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
      - name: agent
        image: ghcr.io/ashishk0224/agent-app:latest
        ports:
        - containerPort: 9999
        livenessProbe:
          httpGet:
            path: /health
            port: 9999
          initialDelaySeconds: 30
          timeoutSeconds: 1
