---
apiVersion: v1
kind: Service
metadata:
  name: splitter
  labels:
    app: splitter
spec:
  type: NodePort
  selector:
    app: splitter
  ports:
  - protocol: TCP
    port: 9997
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: splitter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: splitter
    spec:
      containers:
      - name: splitter
        image: ghcr.io/ashishk0224/splitter-app:latest
        ports:
        - containerPort: 9997
        livenessProbe:
          httpGet:
            path: /health
            port: 9997
          initialDelaySeconds: 30
          timeoutSeconds: 1
