---
apiVersion: v1
kind: Service
metadata:
  name: target
  labels:
    app: target
spec:
  type: NodePort
  selector:
    app: target
  ports:
  - protocol: TCP
    port: 9997
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: target
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: target
    spec:
      containers:
      - name: target
        image: ghcr.io/ashishk0224/target-app:latest
        ports:
        - containerPort: 9997
        livenessProbe:
          httpGet:
            path: /health
            port: 9997
          initialDelaySeconds: 30
          timeoutSeconds: 1
